### ISSUE TITLE
Grammar: more then,less then => more than, less than

### ISSUE THREAD

**Issue by jimthedev** [Baremetrics/select#4]
There is a screenshot in the README and two text usage of the phrase 'more then' or 'less then'. The correct term is 'more than' or 'less than'.

https://camo.githubusercontent.com/82af1ccb89d0569757950ff473aab508c96bd1ab/687474703a2f2f74796c65722e6c696e6b2f644e69482f53637265656e25323053686f74253230323031352d30392d3239253230617425323031322e32392e3139253230504d2e706e67

https://github.com/Baremetrics/select/blame/master/README.md#L59
https://github.com/Baremetrics/select/blame/master/README.md#L63

**Comment by kalepail** [comment]
Fixed: https://github.com/Baremetrics/select/commit/a1cc656b44fc47c546babd5c8420831553332b11

**Comment by jimthedev** [comment]
Nice, thanks.
